# testcase_4die_big 数据集配置
base_path: "./data/testcase_4die_big"

# MCTS参数
sims: 1000
batch: 1000

# Interposer边界（注释掉则从terminal自动计算）
width: 27850
height: 27750

# 后处理优化
search_points: 20
annealing_phases: 100

no_tree: true
