# testcase_4die_mid_a4 数据集配置
base_path: "./data/testcase_4die_mid_a4"

# MCTS参数
sims: 1000
batch: 100

# Interposer边界（注释掉则从terminal自动计算）
width: 25707
height: 25542

# 后处理优化
search_points: 20
annealing_phases: 10

no_tree: true
no_viz: true