# 4die small 测试用例
base_path: "./data/testcase_4die_small_a1"

sims: 2000
seed: 0
batch: 1000
gumbel_scale: 1.0

# Interposer边界（注释掉则从terminal自动计算）
width: 12474
height: 12474

# 后处理优化
initial_step: 200
final_step: 1
search_points: 200
annealing_phases: 10

# 输出
output: "."
no_tree: true
no_viz: false
