# testcase_6die_small_a2 数据集配置
base_path: "./data/testcase_6die_small_a2"

# MCTS参数
sims: 1000
batch: 1000

# Interposer边界（注释掉则从terminal自动计算）
width: 16324
height: 16324

# 后处理优化
search_points: 20
annealing_phases: 100

no_tree: true
